"""путь к изображению книг

Revision ID: 5a78911a6b1f
Revises: 
Create Date: 2021-04-23 18:06:55.885078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a78911a6b1f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('image_path', sa.String(), nullable=True))
    op.drop_index('ix_books_content', table_name='books')
    op.create_index(op.f('ix_books_title'), 'books', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_title'), table_name='books')
    op.create_index('ix_books_content', 'books', ['content'], unique=1)
    op.drop_column('books', 'image_path')
    # ### end Alembic commands ###
