"""добавил user к книге

Revision ID: 675b9ec922ae
Revises: 5a78911a6b1f
Create Date: 2021-04-25 15:09:40.493066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '675b9ec922ae'
down_revision = '5a78911a6b1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'books', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column('books', 'user_id')
    # ### end Alembic commands ###
